server:
  port: 8050

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        # 1. Customer Service Route
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customer/**

        # 2. Account Service Route
        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/account/**, /bank/**

        # 3. Transaction Service Route
        - id: transaction-service
          uri: lb://TRANSACTION-SERVICE
          predicates:
            - Path=/transaction/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

jwt:
  secret: ${JWT_SECRET_KEY:5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437}



