server:
  port: 8051

spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:mysql://localhost:3306/bank_customer_db?useSSL=false&serverTimezone=UTC
    username: test
    password: Pass@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
