server:
  # 8052 is default port if server_port not set
  port: ${SERVER_PORT:8052}
spring:
  application:
    name: account-service
  datasource:
    url: ${ACCOUNT_SERVICE_DB_URI}
    username: ${DB_USER}
    password: ${db_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

customer:
  service:
    url: ${CUSTOMER_DETAILS_URL}